"""Statistics over seeds for the random frustration-free 2-SAT chain of task3b(B).
This is the multidegree-(1,...,1) sector of the ideal generated by bilinear forms
f_i on consecutive blocks, each chosen to vanish on a random product point; it is
an exact sub-block of H_N with N = m, n = 2m-1 (verified in task3b_hard.py),
so gap(sector) is an UPPER BOUND on Delta_N.
"""
import numpy as np
from task3b_hard import two_local, gapof

REPS = 12
print(f"{'m':>3} {'n=2m-1':>7} {'kerdims':>18} {'min Delta':>12} {'median':>12} "
      f"{'max':>12} {'median 1/Delta':>15}")
ms, med = [], []
for m in range(3, 12):
    gaps, kds = [], []
    for s in range(REPS):
        rng = np.random.default_rng(10000 + 137*m + s)
        phis = [rng.normal(size=2) + 1j*rng.normal(size=2) for _ in range(m)]
        phis = [p/np.linalg.norm(p) for p in phis]
        H = np.zeros((2**m, 2**m), dtype=complex)
        for i in range(m-1):
            prod = np.kron(phis[i], phis[i+1])
            w = rng.normal(size=4) + 1j*rng.normal(size=4)
            psi = w - prod*(np.vdot(prod, w)/np.vdot(prod, prod))
            H += two_local(psi/np.linalg.norm(psi), i, i+1, m)
        k, g, nrm = gapof(H)
        gaps.append(g); kds.append(k)
    gaps = np.array(gaps)
    ms.append(m); med.append(np.median(gaps))
    print(f"{m:>3} {2*m-1:>7} {str(sorted(set(kds))):>18} {gaps.min():>12.4g} "
          f"{np.median(gaps):>12.4g} {gaps.max():>12.4g} {1/np.median(gaps):>15.4g}", flush=True)

ms = np.array(ms); med = np.array(med)
pe = np.polyfit(ms, np.log(med), 1)
pp = np.polyfit(np.log(ms), np.log(med), 1)
print(f"\n  exponential fit : median Delta ~ {np.exp(pe[1]):.4g} * exp({pe[0]:+.4f} m)"
      f"   [ratio per site = {np.exp(pe[0]):.4f}]")
print(f"  power-law  fit  : median Delta ~ {np.exp(pp[1]):.4g} * m^({pp[0]:+.3f})")
r_exp = np.corrcoef(ms, np.log(med))[0, 1]
r_pow = np.corrcoef(np.log(ms), np.log(med))[0, 1]
print(f"  |corr| log(Delta) vs m = {abs(r_exp):.4f} ;  vs log m = {abs(r_pow):.4f}"
      f"  -> {'EXPONENTIAL' if abs(r_exp) > abs(r_pow) else 'POWER LAW'} fits better")
