"""Checker: statistics of the random frustration-free 2-local chain gap.

CONVENTIONS: definitions/definitions.md is the single source (rk-light L2).
DEPARTURE FROM convention C5: like the seed's own numerics, generators are
used AS WRITTEN (unit coefficients), not normalised to unit Bombieri-Weyl
norm, so every Delta_N below is the gap of that presentation.  See README.

SEED CLAIM UNDER TEST
  seed/analysis-2026-09-01/report.md, Sect. 7, last paragraph:
    "random frustration-free 2-local chains have median Delta ~ m^-3.5 over
     m <= 11 (a power law fits better than an exponential, but m <= 11 cannot
     exclude a slow exponential)."
  This is the numerical support quoted against Conjecture 8.3(d) being the
  typical case ("typical multigraded instances are not the hard ones").

  The chain is the multidegree-(1,...,1) sector of an ideal generated by
  bilinear forms on consecutive blocks, each vanishing on a random product
  point; the sector identity is verified by check_task3b_hard.py, so this
  gap is an upper bound on Delta_N with N = m and n = 2m-1.

WHAT IS CHECKED (exit 0 only if all hold)
  (1) every sampled chain is frustration free with kernel dimension exactly
      m+1 and Delta > 0 (so "median Delta" is well defined);
  (2) the power-law fit to the medians has exponent in EXP_RANGE
      (published -3.5);
  (3) the power law fits better than an exponential:
      |corr(log median Delta, log m)| > |corr(log median Delta, m)|;
  (4) the medians decay by at least DECAY_MIN between m = 3 and m = MMAX
      (the gap really does close in this sector).

BUDGET: REPS = 12 seeds per m, m = 3..MMAX with MMAX = 11 (2^11 = 2048),
exactly the seed's settings.
"""
import math

import numpy as np

import checkharness
from check_task3b_hard import gapof, two_local

REPS = 12
MMAX = 11
EXP_RANGE = (-4.2, -2.9)
DECAY_MIN = 30.0        # median Delta(m=3) / median Delta(m=MMAX)


def body(ck):
    ck.info(f"  {'m':>3} {'n=2m-1':>7} {'kerdims':>14} {'min Delta':>11} "
            f"{'median':>11} {'max':>11}")
    ms, med = [], []
    for m in range(3, MMAX + 1):
        gaps, kds = [], []
        for s in range(REPS):
            rng = np.random.default_rng(10000 + 137 * m + s)
            phis = [rng.normal(size=2) + 1j * rng.normal(size=2) for _ in range(m)]
            phis = [p / np.linalg.norm(p) for p in phis]
            H = np.zeros((2**m, 2**m), dtype=complex)
            for i in range(m - 1):
                prod = np.kron(phis[i], phis[i + 1])
                w = rng.normal(size=4) + 1j * rng.normal(size=4)
                psi = w - prod * (np.vdot(prod, w) / np.vdot(prod, prod))
                H += two_local(psi / np.linalg.norm(psi), i, i + 1, m)
            k, g, nrm = gapof(H)
            gaps.append(float(g))
            kds.append(k)
        gaps = np.array(gaps)
        ms.append(m)
        med.append(float(np.median(gaps)))
        ck.info(f"  {m:>3} {2*m-1:>7} {str(sorted(set(kds))):>14} "
                f"{gaps.min():>11.4g} {np.median(gaps):>11.4g} "
                f"{gaps.max():>11.4g}")
        ck.equal(sorted(set(kds)), [m + 1],
                 f"m={m}: every sampled chain is frustration free with "
                 f"kernel dimension m+1")
        ck.require(bool((gaps > 0).all()), f"m={m}: every sampled Delta > 0")

    ms = np.array(ms, dtype=float)
    med = np.array(med, dtype=float)
    pe = np.polyfit(ms, np.log(med), 1)
    pp = np.polyfit(np.log(ms), np.log(med), 1)
    r_exp = abs(float(np.corrcoef(ms, np.log(med))[0, 1]))
    r_pow = abs(float(np.corrcoef(np.log(ms), np.log(med))[0, 1]))
    ck.info(f"\n  exponential fit : median Delta ~ {math.exp(pe[1]):.4g} * "
            f"exp({pe[0]:+.4f} m)")
    ck.info(f"  power-law  fit  : median Delta ~ {math.exp(pp[1]):.4g} * "
            f"m^({pp[0]:+.3f})   [published -3.5]")
    ck.info(f"  |corr| vs m = {r_exp:.4f} ; vs log m = {r_pow:.4f}  -> "
            f"{'POWER LAW' if r_pow > r_exp else 'EXPONENTIAL'} fits better")

    ck.between(float(pp[0]), EXP_RANGE[0], EXP_RANGE[1],
               "median Delta: fitted power-law exponent (published -3.5)")
    ck.require(r_pow > r_exp,
               f"a power law must fit better than an exponential: "
               f"|corr| vs log m = {r_pow:.4f} is not > |corr| vs m = {r_exp:.4f}")
    ck.atleast(med[0] / med[-1], DECAY_MIN,
               f"median Delta(m=3)/median Delta(m={MMAX}): the gap closes")


if __name__ == "__main__":
    checkharness.run(
        "task3e_ffstats",
        "report.md Sect. 7: random frustration-free 2-local chains have median "
        f"Delta ~ m^-3.5 over m <= {MMAX} with a power law fitting better than "
        "an exponential; all chains frustration free with kernel dim m+1",
        body)
